linters:
    enable:
        - bodyclose
        - dupl
        - errcheck
        - goconst
        - gofmt
        - goimports
        - gosec
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nakedret
        - prealloc
        - revive
        - staticcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - whitespace

issues:
    exclude-rules:
        - path: _test\.go
          linters:
              - dupl
              - gosec
    exclude-dirs:
        - testdata

linters-settings:
    dupl:
        threshold: 100
    funlen:
        lines: 100
        statements: 50
    gocyclo:
        min-complexity: 15
    goconst:
        min-len: 2
        min-occurrences: 2
    govet:
        shadow: true
    misspell:
        locale: US
    nolintlint:
        allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
        allow-unused: false # report any unused nolint directives
        require-explanation: false # don't require an explanation for nolint directives
        require-specific: false # don't require nolint directives to be specific about which linter is being skipped

run:
    timeout: 5m
