jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Set up Node
        uses: actions/setup-node@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}