name: Go CI

on:
    push:
        branches: [main, master]
        path: "pre-go/**"
    pull_request:
        branches: [main, master]
        path: "pre-go/**"
jobs:
    test-go:
        name: Run tests and collect coverage for Go lib
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23"
                  cache: true
                  cache-dependency-path: "./pre-go/go.sum"

            - name: Install dependencies
              working-directory: ./pre-go
              run: go mod download

            - name: Run tests with coverage
              working-directory: ./pre-go
              run:  go test -coverprofile=coverage.out -covermode=atomic $(go list ./... | grep -v "/mocks" | grep -v "/testutils" | grep -v "/cmd")

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./pre-go/coverage.out
                  flags: go
                  fail_ci_if_error: true
    golangci:
        name: Go linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23"
                  cache: true

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  working-directory: ./pre-go
                  version: v1.60.3
                  args: --timeout=5m

                  # Optional: show only new issues if it's a pull request
                  only-new-issues: ${{ github.event_name == 'pull_request' }}

                  # Optional: if set to true, then all caching functionality will be completely disabled,
                  # takes precedence over all other caching options.
                  # skip-cache: true

                  # Optional: if set to true, then the action won't use any cache directories.
                  # skip-pkg-cache: true
                  # skip-build-cache: true
