name: TypeScript CI

on:
    push:
        branches: [main, master]
        path: "ts/**"
    pull_request:
        branches: [main, master]
        path: "ts/**"

jobs:
    lint:
        name: Lint TypeScript code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
                  cache: "pnpm"
                  cache-dependency-path: "./ts/pnpm-lock.yaml"

            - name: Install dependencies
              working-directory: ./ts
              run: pnpm install --frozen-lockfile

            - name: Run ESLint
              working-directory: ./ts
              run: pnpm lint
